//
//  DayDream.swift
//  Day Dreamer
//
//  Created by Adam Strickland on 3/6/24.
//

import Foundation
import Firebase
import FirebaseFirestoreSwift

struct Day: Identifiable, Codable {
    @DocumentID var id: String? // Autogenerated ID by Firestore
    let title: String
    let selectedDate: Timestamp
    let showTimeDetails: Bool
    let showWeeksDetails: Bool
    let userID: String // To associate the day with a user
}
